In [3]:
import pandas as pd

In [22]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
df=pd.read_excel('Online_Retail.xlsx')

In [4]:
df.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

          InvoiceDate  UnitPrice  CustomerID         Country  
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom  
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom  
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom

In [6]:
df['Description']=df['Description'].str.strip()
# df.dropna(axis=0, subset=['InvoiceNo'], inplace=True)
df['InvoiceNo']=df['InvoiceNo'].astype('str')
df=df[~df['InvoiceNo'].str.contains('C')]

In [8]:
df.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

          InvoiceDate  UnitPrice  CustomerID         Country  
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom  
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom  
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom

In [10]:
basket=(df[df['Country']=='France'].groupby(['InvoiceNo', 'Description'])['Quantity'].sum().unstack().fillna(0))
basket

Description  10 COLOUR SPACEBOY PEN  12 COLOURED PARTY BALLOONS  \
InvoiceNo                                                         
536370                          0.0                         0.0   
536852                          0.0                         0.0   
536974                          0.0                         0.0   
537065                          0.0                         0.0   
537463                          0.0                         0.0   
537468                         24.0                         0.0   
537693                          0.0                         0.0   
537897                          0.0                         0.0   
537967                          0.0                         0.0   
538008                          0.0                         0.0   
538093                          0.0                         0.0   
538196                          0.0                         0.0   
539050                          0.0                         0.0   
539113                          0.0                         0.0   
539407                          0.0                         0.0   
539435                          0.0                         0.0   
539551                          0.0                         0.0   
539607                          0.0                         0.0   
539688                          0.0                         0.0   
539727                          0.0                         0.0   
539829                          0.0                         0.0   
540178                          0.0                         0.0   
540239                          0.0                         0.0   
540351                          0.0                         0.0   
540365                         24.0                         0.0   
540455                          0.0                         0.0   
540463                          0.0                         0.0   
540521                          0.0                         0.0   
540642                          0.0                         0.0   
540688                          0.0                         0.0   
...                             ...                         ...   
578736                          0.0                         0.0   
578835                          0.0                         0.0   
579153                          0.0                         0.0   
579190                          0.0                         0.0   
579193                          0.0                         0.0   
579345                          0.0                         0.0   
579492                          0.0                         0.0   
579529                          0.0                         0.0   
579634                          0.0                         0.0   
579708                          0.0                         0.0   
579792                          0.0                        20.0   
579870                          0.0                         0.0   
580120                          0.0                         0.0   
580126                          0.0                         0.0   
580144                          0.0                         0.0   
580160                          0.0                         0.0   
580285                          0.0                         0.0   
580509                          0.0                         0.0   
580534                          0.0                         0.0   
580536                          0.0                         0.0   
580705                          0.0                         0.0   
580706                          0.0                         0.0   
580736                          0.0                         0.0   
580753                          0.0                         0.0   
580756                          0.0                         0.0   
580986                          0.0                         0.0   
581001                          0.0            

In [16]:
def encode_units(x):
    if x<=0:
        return 0
    if x>=0:
        return 1
basket_sets=basket.applymap(encode_units)
basket_sets.drop('POSTAGE', inplace=True, axis=1)
basket_sets.head()

Description  10 COLOUR SPACEBOY PEN  12 COLOURED PARTY BALLOONS  \
InvoiceNo                                                         
536370                            0                           0   
536852                            0                           0   
536974                            0                           0   
537065                            0                           0   
537463                            0                           0   

Description  12 EGG HOUSE PAINTED WOOD  12 MESSAGE CARDS WITH ENVELOPES  \
InvoiceNo                                                                 
536370                               0                                0   
536852                               0                                0   
536974                               0                                0   
537065                               0                                0   
537463                               0                                0   

Description  12 PENCIL SMALL TUBE WOODLAND  \
InvoiceNo                                    
536370                                   0   
536852                                   0   
536974                                   0   
537065                                   0   
537463                                   0   

Description  12 PENCILS SMALL TUBE RED RETROSPOT  12 PENCILS SMALL TUBE SKULL  \
InvoiceNo                                                                       
536370                                         0                            0   
536852                                         0                            0   
536974                                         0                            0   
537065                                         0                            0   
537463                                         0                            0   

Description  12 PENCILS TALL TUBE POSY  12 PENCILS TALL TUBE RED RETROSPOT  \
InvoiceNo                                                                    
536370                               0                                   0   
536852                               0                                   0   
536974                               0                                   0   
537065                               0                                   0   
537463                               0                                   0   

Description  12 PENCILS TALL TUBE WOODLAND  ...  WRAP VINTAGE PETALS  DESIGN  \
InvoiceNo                                   ...                                
536370                                   0  ...                            0   
536852                                   0  ...                            0   
536974                                   0  ...                            0   
537065                                   0  ...                            0   
537463                                   0  ...                            0   

Description  YELLOW COAT RACK PARIS FASHION  YELLOW GIANT GARDEN THERMOMETER  \
InvoiceNo                                                                      
536370                                    0                                0   
536852                                    0                                0   
536974                                    0                                0   
537065                                    0                                0   
537463                                    0                                0   

Description  YELLOW SHARK HELICOPTER  ZINC  STAR T-LIGHT HOLDER  \
InvoiceNo                                                         
536370                             0                          0   
536852                             0                          0   
536974                             0                          0   
537065                             0                          0   
537463                             0      

In [26]:
frequent_items=apriori(basket_sets, min_support=0.07, use_colnames=True)
rules = association_rules(frequent_items, metric="lift", min_threshold=1)
rules.head()

antecedents                   consequents  \
0  (ALARM CLOCK BAKELIKE GREEN)   (ALARM CLOCK BAKELIKE PINK)   
1   (ALARM CLOCK BAKELIKE PINK)  (ALARM CLOCK BAKELIKE GREEN)   
2  (ALARM CLOCK BAKELIKE GREEN)    (ALARM CLOCK BAKELIKE RED)   
3    (ALARM CLOCK BAKELIKE RED)  (ALARM CLOCK BAKELIKE GREEN)   
4   (ALARM CLOCK BAKELIKE PINK)    (ALARM CLOCK BAKELIKE RED)   

   antecedent support  consequent support   support  confidence      lift  \
0            0.096939            0.102041  0.073980    0.763158  7.478947   
1            0.102041            0.096939  0.073980    0.725000  7.478947   
2            0.096939            0.094388  0.079082    0.815789  8.642959   
3            0.094388            0.096939  0.079082    0.837838  8.642959   
4            0.102041            0.094388  0.073980    0.725000  7.681081   

   leverage  conviction  
0  0.064088    3.791383  
1  0.064088    3.283859  
2  0.069932    4.916181  
3  0.069932    5.568878  
4  0.064348    3.293135

In [29]:
rules[(rules['lift']>=6) & (rules['confidence']>=0.8)]

antecedents  \
2                        (ALARM CLOCK BAKELIKE GREEN)   
3                          (ALARM CLOCK BAKELIKE RED)   
17                    (SET/6 RED SPOTTY PAPER PLATES)   
18                    (SET/6 RED SPOTTY PAPER PLATES)   
19                      (SET/6 RED SPOTTY PAPER CUPS)   
20  (SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...   
21  (SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...   
22  (SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...   

                             consequents  antecedent support  \
2             (ALARM CLOCK BAKELIKE RED)            0.096939   
3           (ALARM CLOCK BAKELIKE GREEN)            0.094388   
17  (SET/20 RED RETROSPOT PAPER NAPKINS)            0.127551   
18         (SET/6 RED SPOTTY PAPER CUPS)            0.127551   
19       (SET/6 RED SPOTTY PAPER PLATES)            0.137755   
20         (SET/6 RED SPOTTY PAPER CUPS)            0.102041   
21  (SET/20 RED RETROSPOT PAPER NAPKINS)            0.122449   
22       (SET/6 RED SPOTTY PAPER PLATES)            0.102041   

    consequent support   support  confidence      lift  leverage  conviction  
2             0.094388  0.079082    0.815789  8.642959  0.069932    4.916181  
3             0.096939  0.079082    0.837838  8.642959  0.069932    5.568878  
17            0.132653  0.102041    0.800000  6.030769  0.085121    4.336735  
18            0.137755  0.122449    0.960000  6.968889  0.104878   21.556122  
19            0.127551  0.122449    0.888889  6.968889  0.104878    7.852041  
20            0.137755  0.099490    0.975000  7.077778  0.085433   34.489796  
21            0.132653  0.099490    0.812500  6.125000  0.083247    4.625850  
22            0.127551  0.099490    0.975000  7.644000  0.086474   34.897959

# Recommended Systems

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
df2 = pd.read_csv('Recommend.csv',names=['user_id', 'movie_id', 'rating', 'timestamp'])
df2.head()

user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [5]:
n_users = df2.user_id.unique().shape[0]
n_movies = df2.movie_id.unique().shape[0]
print(n_users)
print(n_movies)

943
1682


In [8]:
train_data, test_data = train_test_split(df2, test_size=0.25)

In [9]:
train_data_matrix = np.zeros((n_users, n_movies))
for line in train_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    train_data_matrix[line[1]-1, line[2]-1] = line[3] 
    
train_data_matrix

array([[0., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [10]:
test_data_matrix = np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    #[user_id index, movie_id index] = given rating.
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
test_data_matrix

array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
movie_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:, np.newaxis] 
ratings_diff = (train_data_matrix - mean_user_rating) 
user_pred = mean_user_rating + user_similarity.dot(ratings_diff) / np.array([np.abs(user_similarity).sum(axis=1)]).T
user_pred

array([[ 1.61330251,  0.59397675,  0.49468078, ...,  0.28637744,
         0.28390941,  0.28620045],
       [ 1.31751616,  0.30339099,  0.16433622, ..., -0.07670706,
        -0.0788149 , -0.07553013],
       [ 1.37196814,  0.2877119 ,  0.15276026, ..., -0.09511166,
        -0.09639161, -0.09299207],
       ...,
       [ 1.21613956,  0.2326883 ,  0.09889974, ..., -0.13809865,
        -0.14026811, -0.13704228],
       [ 1.38199483,  0.33606739,  0.22577401, ..., -0.01389505,
        -0.01611329, -0.01294212],
       [ 1.4483379 ,  0.42725774,  0.33464745, ...,  0.12538099,
         0.12288123,  0.12550492]])

In [12]:
movie_pred = train_data_matrix.dot(movie_similarity) / np.array([np.abs(movie_similarity).sum(axis=1)])
movie_pred

array([[0.36338661, 0.37369824, 0.38852149, ..., 0.43819314, 0.43545509,
        0.42482758],
       [0.07533719, 0.0874584 , 0.08548579, ..., 0.08914439, 0.08982748,
        0.08947335],
       [0.07094958, 0.07462557, 0.0731975 , ..., 0.06946728, 0.07376562,
        0.07447881],
       ...,
       [0.01846551, 0.02480818, 0.02440344, ..., 0.0278782 , 0.02795955,
        0.02770046],
       [0.12303082, 0.13120856, 0.14023668, ..., 0.14532507, 0.1451517 ,
        0.14502246],
       [0.22116726, 0.21808132, 0.23958018, ..., 0.27820586, 0.27602617,
        0.27049091]])

In [13]:
from sklearn.metrics import mean_squared_error
from math import sqrt
def rmse(pred, test):
    pred = pred[test.nonzero()].flatten() 
    test = test[test.nonzero()].flatten()
    return sqrt(mean_squared_error(pred, test))

In [14]:
rmse(user_pred, test_data_matrix)

3.1300707040803246

In [15]:
rmse(movie_pred, test_data_matrix)

3.45602064952182