In [22]:
import pandas as pd
import numpy as np

#### 1.Extract data from the given SalaryGender CSV file and store the data from each

In [30]:
salgen = pd.read_csv('SalaryGender.csv')

sal=salgen['Salary'].values
gen=salgen['Gender'].values
age=salgen['Age'].values
phd=salgen['PhD'].values

print("Salary Array = \n", sal)
print("\nGender Array = \n", gen)
print("\nAge Array = \n",age)
print("\nPHD Array = \n", phd)

Salary Array = 
 [140.    30.    35.1   30.    80.    30.    60.    31.1  125.    51.
   3.    46.   150.     3.   130.    15.   130.    84.   190.    74.
  73.    10.    50.     7.     9.5   15.2   28.6   20.    72.    81.
 100.    90.    90.    35.    30.    25.    52.     9.    63.    72.
  16.    92.   106.     2.5    9.    32.    32.    55.    52.    28.
  20.    14.7   22.3   34.8   84.    19.   160.    65.    55.     4.6
 102.    20.    62.    55.    45.6   40.    24.    35.    48.    20.
  40.7   15.     0.25 152.    39.8   12.    30.   120.     1.7   36.
  96.    38.    90.     9.    25.8   22.    38.8   72.    89.    41.
  89.    25.    52.   115.    66.    18.6  152.     1.8   35.     4.  ]

Gender Array = 
 [1 0 0 1 0 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0
 0 1 1 1 0 1 1 0 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 1 1 0 1 1 0 0 1 0 0 0 1 0 1
 0 0 1 1 1 1 1 0 1 1 0 0 0 1 1 0 1 0 1 0 0 1 1 1 0 0]

Age Array = 
 [47 65 56 23 53 27 53 30 44 63 22 59 60 28 65 25 65 

#### 2.Find number of men and women with a PhD

In [44]:
men = salgen[(salgen['Gender']==1)&(salgen['PhD']==1)]
women = salgen[(salgen['Gender']==0)&(salgen['PhD']==1)]
print("number of men with a PhD = ", len(men))
print("number of women with a PhD = ", len(women))

number of men with a PhD =  24
number of women with a PhD =  15


#### 3.Store the “Age” and “PhD” columns in one DataFrame and delete the data of all people who don’t have a PhD

In [70]:
age_phd_df = pd.read_csv('SalaryGender.csv', usecols=['Age', 'PhD'] )
print(age_phd_df.head())

index_label=age_phd_df[age_phd_df['PhD']==0].index.tolist()
Nophd = age_phd_df.drop(index=index_label)
print("DataFrame After deleting people who dont have a phd = \n", Nophd)

   Age  PhD
0   47    1
1   65    1
2   56    0
3   23    0
4   53    1
DataFrame After deleting people who dont have a phd = 
     Age  PhD
0    47    1
1    65    1
4    53    1
8    44    1
9    63    1
12   60    1
17   47    1
18   66    1
19   45    1
25   66    1
26   36    1
28   51    1
29   65    1
30   45    1
31   52    1
32   54    1
38   34    1
41   58    1
42   77    1
45   48    1
47   49    1
49   65    1
54   49    1
56   61    1
57   43    1
60   66    1
63   56    1
73   71    1
76   69    1
77   58    1
79   32    1
80   33    1
81   32    1
87   42    1
89   51    1
90   71    1
92   55    1
94   55    1
96   56    1


#### 4.Calculate the total number of people who have a PhD degree from SalaryGender CSV file.

In [79]:
#version1
tot = (salgen['PhD']==1)
print("total number of people who have a PhD degree = \n", sum(tot))
tot[0]

#version2
count=0
for each in tot:
    if each:
        count+=1
    else:
        continue
print("\ntotal number of people who have a PhD degree = \n", count)

total number of people who have a PhD degree = 
 39

total number of people who have a PhD degree = 
 39


#### 5.How do you Count The Number Of Times Each Value Appears In An Array Of Integers

In [85]:
a=[0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]
print("0 comes =",a.count(0), "times")
print("1 comes =",a.count(1), "times")
print("2 comes =",a.count(2), "times")
print("3 comes =",a.count(3), "times")
print("4 comes =",a.count(4), "times")
print("5 comes =",a.count(5), "times")

0 comes = 4 times
1 comes = 2 times
2 comes = 1 times
3 comes = 1 times
4 comes = 3 times
5 comes = 2 times


#### 6.Create a numpy array [[0, 1, 2], [ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]]) and filter the elements greater than 5.

In [116]:
lst6 = [[0, 1, 2], [3, 4, 5],[6,7,8],[9,10,11]]
arr6 = np.array(lst6)
print(arr6[arr6>5])

[ 6  7  8  9 10 11]


#### 7.Create a numpy array having NaN (Not a Number) and print it. Print the same array omitting all elements which are nan

In [152]:
arr7 = np.array([np.nan,1,2,np.nan, 3,4, 5])
print("Original array with naan values = ", arr7)
arr7 = arr7[~np.isnan(arr7)]
print("Array without naan values = ", arr7)

Original array with naan values =  [nan  1.  2. nan  3.  4.  5.]
Array without naan values =  [1. 2. 3. 4. 5.]


#### 8. Create a 10x10 array with random values and find the minimum and maximum values.

In [192]:
import random
randnums= np.random.randint(100,1000,100)
x = randnums.reshape(10,10)
print(x)
print("Maximum Value = ",x.max())
print("Minimum Value = ",x.min())

[[101 538 113 280 524 901 185 245 857 410]
 [634 590 325 281 792 856 118 181 726 149]
 [260 614 182 135 981 837 244 385 112 278]
 [396 370 449 797 969 848 202 638 930 881]
 [697 194 191 780 863 996 523 288 378 706]
 [432 932 142 554 994 948 131 673 219 331]
 [915 622 442 839 435 332 528 777 543 894]
 [449 689 345 609 770 387 681 717 593 661]
 [719 394 289 877 510 902 867 907 419 873]
 [836 325 258 448 216 431 939 109 991 901]]
Maximum Value =  996
Minimum Value =  101


#### 9.Create a random vector of size 30 and find the mean value

In [197]:
ran9 = np.random.randint(100, 300, 30)
y = ran9.reshape(5,6)
print(y)
print("Mean  = ", y.mean())

[[136 258 141 145 228 173]
 [216 109 136 163 113 272]
 [112 249 192 225 239 207]
 [131 253 185 107 293 242]
 [213 268 155 214 139 150]]
Mean  =  188.8


#### 10.Create numpy array having elements 0 to 10 And negate all the elements between 3 and 9

In [207]:
ran10 = np.arange(10)
a=(ran10>=3) & (ran10<=9)
ran10[a]=ran10[a]*-1
ran10

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8, -9])

### 11. Create a random array of 3 rows and 3 columns and sort it according to 1st column, 2nd column or 3rd column.

In [226]:
ran11 = np.random.randint(50, 70, 9)
w = ran11.reshape(3,3)
print(w)
w.sort(axis=0)
print("\ncolumn wise sort")
w

[[67 68 64]
 [51 67 67]
 [54 63 56]]

column wise sort


array([[51, 63, 56],
       [54, 67, 64],
       [67, 68, 67]])

#### 12.Create a four dimensions array get sum over the last two axis at once

In [255]:
ran12 = np.arange(16)
v = ran12.reshape(4,4)
print(v)
print("\nSum of last 2 axis row wise = ",v[2:].sum())
print("\nSum of last 2 axis Column wise = ",v[:, 2:].sum())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Sum of last 2 axis row wise =  92

Sum of last 2 axis Column wise =  68


#### 13.Create a random array and swap two rows of an array

In [266]:
import numpy as np
f = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4]])
print(f)
f[[0,2]]=f[[2,0]]
print("\nrows swapped \n",f)

[[4 3 1]
 [5 7 0]
 [9 9 3]
 [8 2 4]]

rows swapped 
 [[9 9 3]
 [5 7 0]
 [4 3 1]
 [8 2 4]]


#### 14.Create a random matrix and Compute a matrix rank.

In [296]:
A = np.matrix([[1,3,7],[2,8,3],[0,0,3]])
print("Rank of above array  = ",np.linalg.matrix_rank(A))

Rank of above array  =  3


#### 15.Analyse various school--- Solution for this 15 qustion will be uploaded along with Case Study II

######      Solution for this 15 question will be uploaded along with Case Study II